id: IC9C27787
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T03:38:58+00:00'
last_modified: '2022-06-07T21:25:17.586860+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29630
  title: ཀསྨིར་ནས་རྙེད་པའི་ལེགས་སྦྱར་ཆོས་དཔེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EEEB:
      image_group_id: I5631
      title: ''
      total_pages: 412
      order: 1
      base_file: EEEB.txt
    21EB:
      image_group_id: I5632
      title: ''
      total_pages: 374
      order: 2
      base_file: 21EB.txt
    FDFF:
      image_group_id: I5633
      title: ''
      total_pages: 492
      order: 3
      base_file: FDFF.txt
    4FF1:
      image_group_id: I5634
      title: ''
      total_pages: 466
      order: 4
      base_file: 4FF1.txt
    06FC:
      image_group_id: I5635
      title: ''
      total_pages: 710
      order: 5
      base_file: 06FC.txt
    801D:
      image_group_id: I5636
      title: ''
      total_pages: 612
      order: 6
      base_file: 801D.txt
    E460:
      image_group_id: I5637
      title: ''
      total_pages: 1270
      order: 7
      base_file: E460.txt
    DC79:
      image_group_id: I5638
      title: ''
      total_pages: 502
      order: 8
      base_file: DC79.txt
    A9E4:
      image_group_id: I5639
      title: ''
      total_pages: 504
      order: 9
      base_file: A9E4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
